import '../globals.css'
import { Montserrat } from 'next/font/google'
import { Providers } from '../providers'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import messengerLogo from "../../public/messenger.png";
import { Image } from '@nextui-org/react'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
    title: 'Book Tour - Philippine Hop On Hop Off',
    // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className='scroll-smooth'>
        <body className={montserrat.className + ' lightRed'}>
                <Providers>
                    {children}
                </Providers>
                <div class="contact-messenger-con">
                    <a href="https://m.me/philippineshoponhopoff" target="_blank">
                        <Image src={messengerLogo.src} />
                    </a>
                </div>
            </body>
        </html>
    )
}
